# NumPy Arrays

In [ ]:
import numpy as np # numpy is a library for numerical operations

In [ ]:
my_list = [1,2,3,4,5,6,7,8,9,10]
print( type(my_list) )

<class 'list'>


In [ ]:
my_array = np.array(my_list) # convert the list to a numpy array
print( type(my_array) )

<class 'numpy.ndarray'>


In [9]:
np.arange(0,10,2) # create an array with values from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [14]:
print(np.zeros(5)) # create an array of zeros with 5 elements
np.zeros(shape=(2,3)) # create a 2x3 matrix of zeros

[0. 0. 0. 0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(shape=(4,6)) # create a 4x6 matrix of ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.random.seed(101) # set the seed for reproducibility 
# -- this creates random numbers that are the same every time
np.random.randint(0,100,10) # create an array of 10 random integers between 0 and 100

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [39]:
arr1 = np.random.randint(0,100,10) # find the maximum value in the array
print(arr1)
arr2 = np.random.randint(0,100,10) # find the maximum value in the array
print(arr2)

[71 20 27 75  5 49 86 89 63 82]
[77  3 56 14 49 87 52 13 47 49]


In [42]:
print("arr1 min: " + str(arr1.min())) # minimum value
print("arr1 max:" + str(arr1.max())) # maximum value
print("arr1 mean:" + str(arr1.mean())) # average
print("arr1 argmax:" + str(arr1.argmax())) # index of the maximum value
print("arr1 argmin:" + str(arr1.argmin())) # index of the minimum value

arr1 min: 5
arr1 max:89
arr1 mean:56.7
arr1 argmax:7
arr1 argmin:4


In [53]:
arr = np.arange(0,11) # create an array from 0 to 10
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [55]:
arr.shape # get the shape of the array

(11,)

In [ ]:
arr.reshape