In [5]:
import cv2
import numpy as np

In [6]:
cap = cv2.VideoCapture(0)

In [7]:
while True:
    _, frame = cap.read()

    cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    cv2.imshow('Color Detector', cv2.flip(frame, 1))

    if cv2.waitKey(1) == ord('q'):
        break

In [8]:
cap.release()
cv2.destroyAllWindows()

In [20]:
color = [45,215,0]
c = np.uint8([[color]])
hsvC = cv2.cvtColor(c, cv2.COLOR_BGR2HSV)

lower_limit = hsvC[0][0][0] - 10, 100, 100
upper_limit = hsvC[0][0][0] + 10, 100, 100

lower_limit = np.array(lower_limit, dtype=np.uint8)
upper_limit = np.array(upper_limit, dtype=np.uint8)

In [21]:
c

array([[[ 45, 215,   0]]], dtype=uint8)

In [22]:
hsvC

array([[[ 66, 255, 215]]], dtype=uint8)

In [23]:
lower_limit

array([ 56, 100, 100], dtype=uint8)

In [24]:
upper_limit

array([ 76, 100, 100], dtype=uint8)