# What is NumPy?

NumPy is a powerful Python library for numerical computing. It stands for "Numerical Python". 

NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing, data analysis, and machine learning.

Some key features of NumPy include:

1. N-dimensional array object: NumPy provides a powerful `ndarray` object that allows efficient storage and manipulation of homogeneous data. It enables fast mathematical operations on arrays, such as element-wise operations, linear algebra, and statistical computations.

2. Broadcasting: NumPy allows arrays with different shapes to be used in arithmetic operations. This broadcasting feature eliminates the need for explicit loops and enables efficient computation on arrays of different sizes.

3. Mathematical functions: NumPy provides a comprehensive set of mathematical functions for operations like trigonometry, logarithms, exponentials, and more. These functions are optimized for performance and can be applied element-wise to arrays.

4. Integration with other libraries: NumPy integrates well with other Python libraries, such as SciPy, Pandas, and Matplotlib. It serves as the foundation for many scientific computing workflows and provides efficient data structures for these libraries to build upon.

To use NumPy in your code, you need to import it using the `import numpy as np` statement. This allows you to access NumPy's functions and objects using the `np` namespace.

Overall, NumPy is a fundamental library for numerical computing in Python, providing efficient data structures and mathematical functions that are essential for scientific and data-intensive applications.

In [29]:
import os
import sys
import numpy as np

NumPy is often preferred over lists in Python for several reasons:
- **Performance:** NumPy arrays are significantly faster than Python lists for numerical computations due to their optimized C implementation and efficient memory layout.

- **Vectorization:** NumPy allows you to perform operations on entire arrays without explicit loops, leading to cleaner and more concise code. This vectorization often results in further performance gains.

- **Broadcasting:** NumPy's broadcasting capabilities enable seamless operations between arrays of different shapes, simplifying complex computations and eliminating the need for manual shape adjustments.

- **Mathematical Operations:** NumPy provides a vast library of mathematical functions and tools specifically designed for array manipulation, making complex calculations easier to implement and understand.

- **Memory Efficiency:** NumPy arrays typically consume less memory than Python lists, especially when dealing with large datasets, due to their compact representation and efficient data storage.

- **Interoperability:** NumPy integrates well with other scientific computing libraries in Python, such as SciPy, Matplotlib, and Pandas, facilitating data analysis and visualization workflows.


# Init and Size

In [30]:
a = np.array([1,2,3], dtype='int8')
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
b.shape

(3, 3)

In [33]:
b.dtype

dtype('int64')

In [34]:
b.itemsize

8

In [35]:
a.size

3

# Manipulations

In [37]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
b[1,1] = 0 # change center element

In [42]:
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [53]:
b[:2] # specific col

array([[1, 2, 3],
       [4, 0, 6]])

In [54]:
b[2:] # specific row

array([[7, 8, 9]])

In [57]:
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [160]:
before = np.array([[5,4,3,2,1],[10,9,8,7,6]])
print(before)
after = before.reshape((5,2))
print(after)

[[ 5  4  3  2  1]
 [10  9  8  7  6]]
[[ 5  4]
 [ 3  2]
 [ 1 10]
 [ 9  8]
 [ 7  6]]


In [166]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
print(np.vstack([v1,v2,v2,np.ones((5),'int8')]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]]


In [173]:
data = np.loadtxt('data.txt')
print(data)
data > 5

[[1.2 3.4 5.6]
 [7.8 9.  1.1]
 [2.3 4.5 6.7]]


array([[False, False,  True],
       [ True,  True, False],
       [False, False,  True]])

In [175]:
print(v1)
v1[[0,2,4]]

[1 2 3 4 5]


array([1, 3, 5])

# Types

In [77]:
a

array([1, 2, 3], dtype=int8)

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [75]:
np.full((2,4,3), 26) # 2x(4,3)

array([[[26, 26, 26],
        [26, 26, 26],
        [26, 26, 26],
        [26, 26, 26]],

       [[26, 26, 26],
        [26, 26, 26],
        [26, 26, 26],
        [26, 26, 26]]])

In [76]:
np.full_like(a,2)

array([2, 2, 2], dtype=int8)

In [84]:
np.random.rand(3,2)

array([[0.57380375, 0.59405326],
       [0.41718819, 0.47572518],
       [0.52806144, 0.03519601]])

In [102]:
np.random.randint(-7,7,size=(10,15)) # 3x4 matrix with random int [0,7] 

array([[-4, -4,  1,  1, -5,  0, -3,  5, -7,  5,  6, -1,  5, -7,  6],
       [ 0, -1,  5,  1,  5,  1,  6, -5, -4,  1, -2,  6,  5, -5,  1],
       [-5, -2, -2,  6, -3,  1, -3,  0, -4,  6,  6, -5,  0,  1,  0],
       [-2,  6, -2, -3, -3,  6,  5, -2,  3,  5,  3,  1, -2, -3,  4],
       [-1,  3, -4,  3, -1,  4,  5, -2, -4,  1,  3,  2, -1, -4, -3],
       [-7, -7, -7, -1, -7,  5, -6, -5, -7, -2,  6,  4,  0, -1, -3],
       [ 2,  2, -5, -4,  5, -4,  5,  1,  2,  4,  3,  3, -3, -6, -5],
       [ 0,  2, -7, -7,  1,  4,  5, -1, -4,  1, -5,  2, -3,  3, -6],
       [ 6,  4,  3, -5, -4,  2,  6,  0, -6, -1, -3, -4, -6,  1, -3],
       [-6,  0,  4,  5,  4,  2, -1, -1, -5, -6, -5,  5,  3,  1,  0]])

In [111]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Mathing

In [112]:
a

array([1, 2, 3], dtype=int8)

In [119]:
a + a

array([ 4,  8, 12], dtype=int8)

In [121]:
a/a

array([1., 1., 1.])

In [125]:
a

array([2, 4, 6], dtype=int8)

In [126]:
a**2

array([ 4, 16, 36], dtype=int8)

In [127]:
np.cos(a)

array([-0.4163, -0.654 ,  0.96  ], dtype=float16)

In [141]:
a = np.ones((2,2))
print('a:', a)
b = np.full((2,3), 2)
print('b:', b)

a: [[1. 1.]
 [1. 1.]]
b: [[2 2 2]
 [2 2 2]]


In [144]:
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [146]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.linalg.det(c)

1.0

# Statistics

In [150]:
stat = np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
print(np.min(stat))
print(np.max(stat))
print(np.sum(stat))

1
6
21


6